---
development:
  cloud_name: mikrondok
  api_key: '446215515862395'
  api_secret: trHUwSIcgxVpv1TavidJsju3Dl8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: mikrondok
  api_key: '446215515862395'
  api_secret: trHUwSIcgxVpv1TavidJsju3Dl8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mikrondok
  api_key: '446215515862395'
  api_secret: trHUwSIcgxVpv1TavidJsju3Dl8
  enhance_image_tag: true
  static_image_support: false