source 'https://rubygems.org'
ruby '2.2.2'

# env variables
gem 'dotenv-rails'
gem 'dotenv-heroku'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'foundation-rails', '5.5.1.0'

#Paginate products
gem 'will_paginate', '~> 3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'carrierwave'
gem 'cloudinary'

# ActiveAdmin
gem 'activeadmin'

# Devise Authentication
gem 'devise'
gem 'devise_security_extension'

# Email validator for devise_security_extension
gem 'rails_email_validator'

# CanCan Authorization
gem 'cancancan', '~> 1.10'

# reCaptcha for devise_security_extension
gem 'recaptcha'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-gplus', '~> 2.0'

# ActiveMerchant for payment
gem 'activemerchant'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Windows does not provide tz-info
gem 'tzinfo-data', platforms: [:mingw, :mswin]

group :production do
  # Puma Webserver for deployment on Heroku
  gem 'puma'

  # Use PostgreSQL for deployment as the database for Active Record
  gem 'pg'

  # Logging on Heroku
  gem 'rails_12factor'
end

group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'

  # Mailer
  gem 'foreman'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Factory-Girl for unit tests
  gem 'factory_girl_rails'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '1.3.6'
end

group :test do
  # Cucumber
  gem 'cucumber-rails', require: false
  gem 'database_cleaner', '~> 1.4.1'
  gem 'launchy'
  gem 'watir-webdriver'

  # minitest
  gem 'minitest-reporters'

  # functionals
  gem 'assert_json'
end

